config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

get 'tds', to: 'tds#index'
get 'td_info', to: 'tds#td_info', as: 'info'
get 'td_form', to: 'tds#td_form', as: 'form'
get '/edit_td', to: 'tds#edit', as: 'edit_td'
post '/save_edit', to: 'tds#save_edit', as: 'save_edit'
post '/create_td', to: 'tds#create', as: 'create_td'
post '/projects/:project_id/issues/:issue_id/tds', to: 'tds#create', as: 'issue_tds'
delete '/projects/:project_id/tds/:id', to: 'tds#destroy', as: 'td'
 

app/models/td.rb
class Td < ActiveRecord::Base

  belongs_to :issue, dependent: :destroy

  def set_type(type)
    self.td_type = type
  end
end

app/controllers/tds_controller.rb
class TdsController < ApplicationController

  def index
    @project = Project.find(params[:project_id])
    @tds = Td.includes(:issue).all
  end

  def td_info
    @project = Project.find(params[:project_id])
    @td = Td.includes(:issue).find(params[:id])
    
    render :template => 'tds/td_info'
  end

  def td_form
    @project = Project.find(params[:project_id])
    @issues = @project.issues

    render :template => 'tds/td_form'
  end

  def edit
    @project = Project.find(params[:project_id])    
    @td = Td.find(params[:id])
    @reload_to = params[:reload_to]
    
    render :template => 'tds/edit_td'
  end

  def save_edit
    td = Td.find(params[:id])
    td.set_type(params[:td_type])

    if params[:reload_to] == "tds"
        redirect_to tds_path(project_id: params[:project_id])
    else
        redirect_to info_path(project_id: params[:project_id], id: params[:id])
    end

    if td.save
      flash[:notice] = 'Edição salva com sucesso.'
    else
      flash[:error] = "Erro ao salvar edição."
    end
  end

  def create
    td = Td.new
    td.td_type = params[:td_type]
    td.issue_id = params[:issue_id]

    redirect_to tds_path(project_id: params[:project_id])
    if td.save
      flash[:notice] = 'TD created successfully.'
    else
      flash.now[:error] = 'TD creation failed.'
    end
  end

  def destroy
    @td = Td.find(params[:id])
    @td.destroy
    
    redirect_to tds_path(project_id: params[:project_id])
  end

end

app/helpers/tds_helper.rb
module TdsHelper
end

app/views/tds/edit_td.html.erb
<head>
    <title>Edit TD</title>
    <%= stylesheet_link_tag 'edit_td', plugin: 'tds' %>

</head>

<body>

    <h2> <%= @td.td_type%> #<%= @td.id%> </h2>
    <div class="main">
        <%= form_with url: save_edit_path, method: :post, local: true do |form| %>
            <%= form.hidden_field :project_id, value: @project.id %>
            <%= form.hidden_field :id, value: @td.id %>
            <%= form.hidden_field :reload_to, value: @reload_to %>
            <div class="field">
                <div class="field label">
                    <%= form.label :td_type %>
                </div>
                <div class="field input">
                    <%= form.select :td_type, ['Requisitos', 'Testes', 'Usabilidade'] %>
                </div>
            </div>
            </div>
            <div class="actions">
                <%= form.submit "Confirm" %>
            </div>
        <% end %>
    </div>
    
</body>

app/views/tds/index.html.erb
<head>

    <title>TDs</title>
    <%= stylesheet_link_tag 'td_index', plugin: 'tds' %>

</head>
<body>
    
    <% if User.current.allowed_to?(:create_tds, @project) %>
        <div class='new-issue'>
            <%= link_to 'New TD', form_path(project_id: @project), method: :get, class: "icon icon-add" %>
        </div>
    <% end %>

    <h2>TDs</h2>

    <table>
      <thead class='table-head'>

        <tr>
        	<th>Issue ID</th>
        	<th>TD ID</th>
        	<th>Type</th>
        	<th>Tracker</th>
        	<th>Status</th>
        	<th>Subject</th>
        	<th>Assignee</th>
            <% if User.current.allowed_to?(:edit_tds, @project) %>
                <th>Edit</th>
            <% end %>
            <% if User.current.allowed_to?(:delete_tds, @project) %>
                <th>Delete</th>
            <% end %>
        </tr>

      </thead>

      <tbody class='table-body'>
        <% cont = 1 %>
        <% @tds.each do |td| %>
           <% if cont == 2 %>
                <tr style='background-color: #ffffff'>
                <% cont = 1 %>
           <% else %>
                <tr style='background-color: #f6f7f8'>
                <% cont = 2 %>
           <% end %>
	            <td><%= td.issue.id %></td>
        	    <td><%= td.id %></td>
        	    <td><%= link_to td.td_type, info_path(project_id: @project, id: td.id), method: :get %></td>
        	    <td><%= td.issue.tracker %></td>
        	    <td><%= td.issue.status %></td>
        	    <td><%= td.issue.subject %></td>
        	    <td><%= td.issue.assigned_to %></td>
                <% if User.current.allowed_to?(:edit_tds, @project) %>
                    <td><%= link_to 'Edit', edit_td_path(id: td[:id], project_id: @project, reload_to: "tds"), method: :get %></td>
                <% end %>
                <% if User.current.allowed_to?(:delete_tds, @project) %>
                    <td><%= link_to 'Delete', td_path(project_id: @project, id: td), method: :delete %></td>
                <% end %>
                </tr>
        <% end %>
      </tbody>
    </table>
</body>

app/views/tds/td_form.html.erb
<head>

    <title>New TD</title>
    <%= stylesheet_link_tag 'td_form', plugin: 'tds' %>
</head>

<body>

    <h2> New TD </h2>
    <div class="main">
        <%= form_with url: create_td_path, method: :post, local: true do |form| %>
            <%= form.hidden_field :project_id, value: @project.id %>
            <div class="field">
                <div class="field label">
                    <%= form.label :td_type %>
                </div>
                <div class="field input">
                    <%= form.select :td_type, ['Requisitos', 'Testes', 'Usabilidade'] %>
                </div>
            </div>
            <div class="field">
                <div class="field label">
                    <%= form.label :issue_id %>
                </div>
                <div class="field input">
                    <%= form.collection_select :issue_id, @issues, :id, lambda {|issue| "#{issue.subject} (##{issue.id})"} %>
                </div>            
            </div>
            <div class="actions">
                <%= form.submit "Create TD" %>
            </div>
        <% end %>
    </div>
</body>

app/views/tds/td_info.html.erb
<head>

    <title><%= @td.td_type %> #<%= @td.id %></title>
    <%= stylesheet_link_tag 'td_info', plugin: 'tds' %>

</head>

<div class='buttons'>
    <% if User.current.allowed_to?(:edit_tds, @project) %>
        <%= link_to 'Edit', edit_td_path(project_id: @project, id: @td.id, reload_to: "info"), method: :get, class: "icon icon-edit" %>
    <% end %>
    
    <% if User.current.allowed_to?(:delete_tds, @project) %>
        <%= link_to 'Delete', td_path(project_id: @project, id: @td.id), method: :delete, class: "icon icon-del" %>
    <% end %>
    
</div>

<h2><%= @td.td_type %> #<%= @td.id %></h2>

<div class='main'>

    <h3>Issue: <%= @td.issue.subject %></h3>
    <% if @td.issue.description != ''%>
        <p>
            <%= @td.issue.description %>
        </p>
    <% end %>

    <div class="attributes">
        <div class="attributes left">
            <div class="attribute">
                <div class="label">Td type: </div>
                <div class="value"><%= @td.td_type%></div>
            </div>
            <div class="attribute">
                <div class="label">Status: </div>
                <div class="value"><%= @td.issue.status%></div>
            </div>
            <div class="attribute">
                <div class="label">Priority: </div>
                <div class="value"><%= @td.issue.priority%></div>
            </div>
            <div class="attribute">
                <div class="label">Assignee: </div>
                <div class="value">
                    <% if @td.issue.assigned_to %>
                        <%= @td.issue.assigned_to.name %>
                    <% else %>
                        -
                    <% end %>
                </div>
            </div>
            <div class="attribute">
                <div class="label">Category: </div>
                <div class="value">
                    <% if @td.issue.category %>
                        <%= @td.issue.category.name %>
                    <% else %>
                        -
                    <% end %>
                </div>
            </div>
        </div>
        <div class="attributes right">
            <div class="attribute">
                <div class="label">Start date: </div>
                <div class="value">
                    <% if @td.issue.start_date %>
                        <%= @td.issue.start_date.to_s(:long)%>
                    <% else %>
                        -
                    <% end %>
                </div>
            </div>
            <div class="attribute">
                <div class="label">Due date: </div>
                <div class="value">
                    <% if @td.issue.due_date %>
                        <%= @td.issue.due_date.to_s(:long)%>
                    <% else %>
                        -
                    <% end %>
                </div>
            </div>
            <div class="attribute">
                <div class="label">% Done: </div>
                <div class="value"><%= @td.issue.done_ratio%>%</div>
            </div>
            <div class="attribute">
                <div class="label">Estimated time: </div>
                <div class="value">
                    <% if @td.issue.estimated_hours %>
                        <%= @td.issue.estimated_hours %> hours
                    <% else %>
                        -
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>